app/models.py
from . import db, app


class Municipio(db.Model):
    __tablename__ = 'tb_municipios'
    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.String(64))
    codigo_ibge = db.Column(db.Integer)
    url = db.Column(db.Text)

    def __repr__(self):
        return '<Municipio %r>' % (self.nome)

app/main/forms.py
from flask_wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class SearchForm(Form):
    search = StringField('search', [DataRequired()])
    submit = SubmitField('Buscar',
                       render_kw={'class': 'btn btn-success btn-block'})

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
# from whoosh.analysis import StemmingAnalyzer
# from flask_moment import Moment
# from flask_debugtoolbar import DebugToolbarExtension
from config import config


db = SQLAlchemy()

# moment = Moment()
# toolbar = DebugToolbarExtension()
app = Flask(__name__)


def create_app(config_name):

    # app.config['WHOOSH_ANALYZER'] = StemmingAnalyzer()
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    # toolbar.init_app(app)
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template, request, url_for, redirect
from .forms import SearchForm
from . import main
from .. import db
from ..models import Municipio
import requests
import json
from sqlalchemy import or_


@main.route('/atualizar')
def atualizar():
    r = requests.get('https://api.brasil.io/mg/', verify=False)
    data_json = json.loads(r.content.decode('utf-8'))

    for data in data_json['municipios']:
        municipio = Municipio.query.filter_by(nome=data['nome']).first()
        if municipio is None:
            m = Municipio()
            m.nome = data['nome']
            m.url = data['url']
            m.codigo_ibge = data['codigo-ibge']
            db.session.add(m)
    db.session.commit()
    return redirect(url_for('.index'))


@main.route('/', methods=['GET', 'POST'])
def index():
    search = SearchForm()
    page = request.args.get('page', 1, type=int)
    pagination = Municipio.query.order_by('nome').paginate(page, per_page=10, error_out=False)
    municipios = pagination.items
    return render_template('index.html', form=municipios, pagination=pagination, formSearch=search)


@main.route('/search', methods=['POST'])
def search():
    form = SearchForm()
    if form.validate_on_submit():
        return redirect(url_for('main.search_results', query=form.search.data))
    return redirect(url_for('index'))


@main.route('/search_results/<query>')
def search_results(query):
    search = SearchForm()
    page = request.args.get('page', 1, type=int)
    pagination = Municipio.query.filter(or_(Municipio.nome.like("%"+query+"%"), Municipio.codigo_ibge.like("%"+query+"%"))).paginate(page, per_page=10, error_out=False)
    municipios = pagination.items
    return render_template('search.html',
                           query=query,
                           form=municipios,
                           pagination=pagination,
                           formSearch=search)

app/templates/_macro.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/index.html
{% import "_macro.html" as macros %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
  </head>
  <body>
    <div class="container">
      <div class="page-header">
        <span>
          <a href="{{url_for('main.atualizar')}}" type="button" class="btn btn-success">Atualizar</a>
        </span>
        <form action="{{ url_for('main.search')}}" class="navbar-form navbar-right" method="POST">
          {{ formSearch.hidden_tag() }}
          <div class="input-group">
            {{ formSearch.search() }}
            <span class="input-group-btn">
              {{ formSearch.submit() }}
            </span>
          </div>
        </form>
        <h1 class="">Lista de cidades</h1>
      </div>
      <div class="row">
        <div class="span12">
          {% if form %}
          <table class="table table-striped">
            <thead>
              <tr>
                <td>Cidade</td>
                <td>Codigo IBGE</td>
                <td>URL</td>
              </tr>
            </thead>
            <tbody>

              {% for m in form %}
              <tr>
                <td>{{m.nome}}</td>
                <td>{{m.codigo_ibge}}</td>
                <td><a href="{{m.url}}" target="_blank">{{m.url}}</a></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <div class="pagination">
          {{ macros.pagination_widget(pagination, '.index') }}
          </div>
          {% else %}
            <h1>Atualize o banco</h1>
          {% endif %}
        </div>
      </div>
    </div>
  </body>
</html>

app/templates/search.html
{% import "_macro.html" as macros %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
  </head>
  <body>
    <div class="container">
      <div class="page-header">
        <span>
          <a href="{{url_for('main.atualizar')}}" type="button" class="btn btn-success">Atualizar</a>
        </span>
        <form action="{{ url_for('main.search')}}" class="navbar-form navbar-right" method="POST">
          {{ formSearch.hidden_tag() }}
          <div class="input-group">
            {{ formSearch.search() }}
            <span class="input-group-btn">
              {{ formSearch.submit() }}
            </span>
          </div>
        </form>
        <h1 class="">Lista de cidades</h1>
      </div>
      <div class="row">
        <div class="span12">
          <table class="table table-striped">
            <thead>
              <tr>
                <td>Cidade</td>
                <td>Codigo IBGE</td>
                <td>URL</td>
              </tr>
            </thead>
            <tbody>

              {% for m in form %}
              <tr>
                <td>{{m.nome}}</td>
                <td>{{m.codigo_ibge}}</td>
                <td><a href="{{m.url}}" target="_blank">{{m.url}}</a></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <div class="pagination">
          {{ macros.pagination_widget(pagination, '.index') }}
          </div>

        </div>
      </div>
    </div>
  </body>
</html>